# Generated by Django 2.2 on 2019-04-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('weather', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('rental', models.CharField(max_length=255)),
                ('buy', models.CharField(max_length=400)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='surf_app.Spot')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='surf_app.Spot')),
            ],
        ),
    ]
