# Generated by Django 2.2 on 2019-04-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surf_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='weather',
        ),
    ]
